version: '3.4'

services:
  quanlydangkymonhocvathuphisvbackend:
    image: quanlydangkymonhocvathuphisvbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.production  
    ports:
      - 3000:3000
