version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SE104
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
