version: '3.4'

services:
  quanlydangkymonhocvathuphisvbackend:
    image: quanlydangkymonhocvathuphisvbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      CI: true
      HUSKY: 0
      
      
    ports:
      - 3000:3000
