version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_HOST: ${DATABASE_HOST}
    ports:
      - 5432:5432
